composer.json
composer.lock

When using the original `http` I get the following error:
```
- Installing ckeditor/templates (4.5.7): Downloading
[Composer\Downloader\TransportException]
Your configuration does not allow connections to http://download.ckeditor.com/templates/releases/templates_4.5.7.zip. See https://getcomposer.org/doc/06-config.md#secure-http for details.
```
I cant see a reason why we wouldnt use https for this...

Change ckeditor/templates url to https

---

scripts/test.sh

Running php lint across the whole code base took a while, so this will only lint the changed files.
I also changed calling core's phpunit tests so they run only if something has changed in core.
I'm ignoring the case of the master branch for now - will be looking into what kind of testing to do on develop and master branches next.

Run php lint on modified php files

---

Dockerfile

Currently these are being installed each circle build, which is adding 30+ seconds to the build. By adding them to the docker image, we wont need to do it every build so it should be faster.
After this is merged to develop, it will take a little while for docker hub to update [the docker image](https://hub.docker.com/r/govau/dta-website-rebuild/), but after that's done I will add a new PR to remove these lines from circle.

Add libpng-dev and gd php extension

---

.circleci/config.yml
.circleci/init.sh
composer.json
scripts/buildrc
scripts/int-test.sh

I wanted to make a change to `scripts/preprocess.sh`, but then realised that I wouldnt be able to test it until I did a `cf push`. So I've made it now run as part of the integration test in circle. 
There might be some more room for improvement, but I spent far too long wrestling with `drush config-import` and I think this can be merged now.

Test preprocess.sh as part of the integration test initialisation

---

.circleci/config.yml
docker-compose.yml

I havent noticed any issues using mariadb, but we should probably match [the RDS broker's mysql that is used on cloud.gov.au](https://github.com/AusDTO/pe-rds-broker/blob/master/config-govau.yml#L122)

Use mysql 5.7 in docker and circle so we match cloud.gov.au

---

Dockerfile

I just noticed that when running `composer install` locally in the docker image, I got this error: 
```
> PhantomInstaller\Installer::installPhantomJS
/app/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory
Caught exception while checking PhantomJS version:
Undefined offset: 0
- Installing phantomjs (2.1.1): Downloading (100%)
```
Havent noticed any problems, and circleci doesnt give this error, but we may as well add this dependency to docker.

Add libfontconfig

---

composer.json
composer.lock

I was having this error during `composer install`:
```
- The requested package drupal/redirect ^1.x-dev exists as drupal/redirect[dev-1.x, 1.x-dev, 1.1.0, 1.0.0, 1.0.0-beta1, 1.0.0-alpha5, 1.0.0-alpha4, 1.0.0-alpha3, 1.0.0-alpha2, 1.0.0-alpha1] but these are rejected by your constraint.
```
I think the caret should be removed when using dev releases, seems to fix it for me anyway

Remove drupal/redirect caret version range

---

.circleci/config.yml

secure-http is now set to false in composer.json, so no need for this kludge

Remove ckeditor s/http/https kludge

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.blog_post.full.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.govcms_event.full.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.landing_page.full.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.landing_page_level_2.full.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.news_item.full.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.page.full.yml

This commit moves the `.au-introduction` class from a surrounding `<div>` to the `<p>` and removes the `<div>`.

Introduction

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.landing_page.field_related_content.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.landing_page_level_2.field_related_content.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.page.field_related_content.yml

This commit updates the entity reference field on Landing pages (levels 1 and 2) and pages to use an ordinary entity reference rather than an entity view.

Update entity reference field

---

scripts/preprocess.sh

(as it locks the site up while it happens)

Change rebuild to only happen on first instance so that tasks don't kick this off

---

.bp-config/php/php.ini.d/extensions.ini
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/login_security.settings.yml

These modules are already included in PHP/CF Buildpack. Installing them via `.bp-config/php/php.ini.d/extensions.ini` caused the system to report multiple instances of modules being installed.
This commit also adds a configuration for `login_security`.
Some database cleanup was required to remove the `import_recruiterbox` module completely. This has been performed on all sites.

Removed unnecessary PHP modules

---

.circleci/config.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.assessment_report.teaser.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.taxonomy_term.blog_authors.default.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/search_api.server.database_search.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/views.view.dss_assessment_results.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/workflows.workflow.editorial.yml

This maintenance update:
- Adds the `start.sh` script to the deployment pipeline for Circle.
- Updates the assessment report content type slightly.
- Updates the blog authors taxonomy.
- Removes the requirement for published content from the DSS Assessment Results view.
- Adds the assessment reports content type to the Editorial workflow.

Minor updates

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/views.view.assessment_reports.yml

This commit simply adds spaces to the assessment report view using twig concatenation (~).

Minor fix for the assessment reports page

---

composer.json
composer.lock
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/mailchimp.settings.yml
docroot/sites/default/settings.php

This commit replace the Mailchimp API key with a fake one, and updates `settings.php` to access the additional info in the UPS.

Replace the Mailchimp API key

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/user.role.anonymous.yml

This commit merely turns off commenting for anonymous users by updating the permissions so the system can be deployed without making it live.

Turn off commenting

---

composer.json
composer.lock
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.blog_post.full.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.news_item.full.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.extension.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_tags.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/views.view.taxonomy_term.yml

This commit resolves an ongoing problem discovered during user research: users expect to be able to navigate across content through tags. This commit adds the functionality.
- Adds links to tags on the blog post and news item full display mode.
- Removes the kint module.
- Updates rabbit hole behaviour.
- Updates the taxonomy term view.
- Updates the theme to 1.5.3.

Making tags functional

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.base_field_override.node.miscellaneous_file.promote.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.base_field_override.node.miscellaneous_file.status.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_form_display.node.miscellaneous_file.default.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.miscellaneous_file.default.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.miscellaneous_file.teaser.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.miscellaneous_file.field_file.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.storage.node.field_file.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/node.type.miscellaneous_file.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/rabbit_hole.behavior_settings.node_type_miscellaneous_file.yml

This commit adds a content type for uploading miscellaneous HTML files. This is ostensibly to enable the respond.js proxy system, but could also be used to upload any other file for hosting purposes.

HTML file upload

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.blog_post.search_result.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.landing_page.search_result.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.landing_page_level_2.search_result.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.news_item.search_result.yml

This commit updates the display modes for the 'Search results' for some content types to remove some rogue HTML which was no being escaped properly.

Update to display modes

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.assessment_report.full.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.assessment_report.field_dss_assessment.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/filter.format.rich_text.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/views.view.dss_assessment_results.yml

This commit updates a few minor configurations:
- Removes label for the DSS assessment block
- Removes the `required` flag from the DSS assessment field.
- Adds `<figure>` and `<figcaption>` tags to the Rich Text format.
- Removes the table caption from the assessment results table and adds a header to make the title dynamic.

Minor configuration update

---

composer.json
composer.lock
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/block.block.booknavigation.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/block.block.booknavigation_2.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/block.block.breadcrumbs_2.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/block.block.dtslandingpagecontent.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/block.block.socialauthlogin.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/block.block.views_block__digital_transformation_strategy_themes_block_1.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/block.block.views_block__digital_transformation_strategy_themes_block_2.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/block.block.views_block__roadmaps_2_block_1.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_form_display.node.roadmap_2_user_experience_.default.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.roadmap_2_user_experience_.default.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.roadmap_2_user_experience_.field_accelerated.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.storage.node.field_accelerated.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.storage.node.field_audience.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/views.view.roadmaps_2.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/wysiwyg_template.wysiwyg_template.accordion.yml

This config update:
- Removes the book nav.
- Changes the weights of a bunch of blocks as a result
- Adds a new field to the Roadmap 2018 content type and updates the Roadmap view to add the 'accelerated' class.
- Updates the 'audience' field to correct the titles.
- Enables the accordion template for book pages.
It also updates the theme to 1.7.4.

Update to config

---

composer.json
composer.lock
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.book.full.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.news_item.full.yml

This commit updates the config for the news item full display to fix incorrectly indented tags and other information. It updates the theme to 1.8.0 which includes the related style update.

Fix for indented images on blog pages

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.image.teaser.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.blog_post.field_facebook_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.blog_post.field_index_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.blog_post.field_linkedin_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.blog_post.field_twitter_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.landing_page.field_facebook_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.landing_page.field_index_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.landing_page.field_linkedin_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.landing_page.field_twitter_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.landing_page_level_2.field_facebook_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.landing_page_level_2.field_index_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.landing_page_level_2.field_linkedin_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.landing_page_level_2.field_twitter_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.news_item.field_facebook_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.news_item.field_index_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.news_item.field_linkedin_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.news_item.field_twitter_image.yml

This commit updates the configuration for image fields on most content types to relax somewhat the restrictions on images sizes, primarily to allow square images.

Content type image configuration update

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/extlink.settings.yml

This commit stops the footer and documents from having external link icons.

Update to extlink settings

---

.circleci/config.yml
scripts/cron.sh

When we create the task, we assign a unique name to it. Then afterwards we can check the output of `cf tasks appname` and check for one of the status strings. I'm just checking for SUCCEEDED, otherwise we will get an error notification via circle. Should do the trick.
https://docs.cloudfoundry.org/devguide/using-tasks.html#-list-tasks-running-on-an-application

Monitor cron job result

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.news_item.field_index_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.page.field_index_image.yml

This commit makes the index image required for news items, and not required for pages.

Update index image requiredness

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.landing_page_level_2.full.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/ds.field.landing_page_cards_2_card_row.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/views.view.related_links.yml

This commit updates landing page views, both menu children and related links, to be 2-up blocks instead of three.

Update to landing page views

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/block.block.dta_gov_au_views_block__contact_module_block_1.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/block.block.mailchimpsubscriptionformsignupforupdates.yml
tests/behat/behat.yml
tests/behat/features/engagement/mailchimp.feature

This commit adds the standalone mailchimp form to the Subscribe page. Also adds tests.

Add standalone mailchimp form

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/metatag.metatag_defaults.node__news_item.yml

This commit fixes an issue with the metatag defaults which was causing images not to appear in Facebook and Twitter posts correctly.

Update metatag defaults

---

docroot/sites/default/settings.php

This commit fixes the error logging levels across the environments from `verbose` in the lower levels to `hide` in production.

Fix error logging

---

composer.json

This patch resolves an issue with authors not being able to save content because book access is checked even for content not in a book.

Error when saving non-book content

---

composer.json
composer.lock
drupal-org-core.make

Another patch for core to resolve the issue with authors not being able to select unpublished nodes as menu parents.

Patch for core

---

composer.json
composer.lock
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.blog_post.home_page_blog_card.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.news_item.card.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.news_item.home_page_blog_card.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_mode.node.home_page_blog_card.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/views.view.news_and_blogs_facets.yml
tests/behat/features/ui/related-links.feature

This commit updates and adds to existing display modes to make sure related links with images (notably blogs) display their summaries correctly. It also updates the theme to 1.9.12, which includes some minor changes to make the new display modes look correct.

Ensure blog summaries show in related links

---

scripts/cron.sh
scripts/deploy.sh
scripts/post-deploy.sh

cloud.gov.au will start managing this project's CF_* env vars in circleci, and to
make it easier for us we need to have a standard naming convention for environment
variables across all repos we look after.
Nothing should change for this project, this is really just house cleaning to use
the standard names.
The standard naming convention is:
CF_API_PROD
CF_API_STAGING
CF_ORG
CF_PASSWORD_PROD
CF_PASSWORD_STAGING
CF_SPACE
CF_USERNAME
After this has been merged we can remove any CF_* env vars in circleci that arent
in the above list.

Use cloud.gov.au naming convention for env vars in circleci

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/linkit.linkit_profile.default.yml

This commit prevents roadmap items from being displayed with the LinkIt tool.

Remove roadmap items from LinkIt

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_form_display.node.media_release.default.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/editor.editor.full_rich_text.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.assessment_report.field_body.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.assessment_report.field_introduction.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.assessment_report.field_pass_rationale.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.assessment_report.field_recommendations.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.blog_post.field_body.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.book.field_body.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.govcms_event.field_body.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.home_page.body.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.landing_page.field_body.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.landing_page_level_2.field_body.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.media_release.field_body.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.news_item.field_body.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.page.field_body.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.node.platforms_and_services.field_body.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.storage.node.body.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.storage.node.field_introduction.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.storage.node.field_pass_rationale.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.storage.node.field_recommendations.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/filter.format.full_rich_text.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/user.role.content_approver.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/user.role.content_editor.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/user.role.digital_transformation_guide_approver.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/user.role.digital_transformation_guide_author.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/user.role.media_release_author.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/user.role.technical_reviewer.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/user.role.webform_author.yml

This commit adds a new text format, 'Full rich'. It also updates the 'Commenting' text format to be 'Simple rich'. The Full rich editor replaces all instances of the 'Full HTML' editor, while Simple rich is used only on media releases.

Update text formats

---

composer.json
composer.lock
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_form_display.taxonomy_term.presentation_type.default.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.home_page.default.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.node.speaker_bio.full.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/core.entity_view_display.taxonomy_term.presentation_type.default.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.field.taxonomy_term.presentation_type.field_index_image.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/field.storage.taxonomy_term.field_index_image.yml

This commit updates event-related content types, notably the presentation type taxonomy to include an image. Also updates the theme to 1.9.27.

Update event content types

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/filter.format.full_rich_text.yml
tests/behat/features/content/toc.feature

This commit fixes a bug in the Full Rich Text editor which was making ToCs appear automatically.

Prevent ToCs from appearing automatically

---

docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/views.view.landing_page_cards.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/views.view.related_content.yml
docroot/sites/default/files/config_SKRbKjrsGZbCwa_q0wg8DYZpUGb3pdwwxawoq_xE0FXjABmFBcdqfoyLjvWYMn74C7COWTFr6w/sync/views.view.related_links.yml

This minor change prevents archived content appearing in cards for those with site permissions. It also prevents archived content appearing in related content entity reference views.

Prevent archived cards showing up
